//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2EnvironmentResetRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2EnvironmentReset";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public BotParamsMsg bot_params;

        public UC2EnvironmentResetRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.bot_params = new BotParamsMsg();
        }

        public UC2EnvironmentResetRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, BotParamsMsg bot_params)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.bot_params = bot_params;
        }

        public static UC2EnvironmentResetRequest Deserialize(MessageDeserializer deserializer) => new UC2EnvironmentResetRequest(deserializer);

        private UC2EnvironmentResetRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.bot_params = BotParamsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.bot_params);
        }

        public override string ToString()
        {
            return "UC2EnvironmentResetRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\nbot_params: " + bot_params.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
