//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC3EnvironmentStepRequest : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC3EnvironmentStep";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg request_sent_timestamp;
        public UC3AgentActionMsg action;
        public UC3AgentActionMsg target_action;

        public UC3EnvironmentStepRequest()
        {
            this.request_sent_timestamp = new BuiltinInterfaces.TimeMsg();
            this.action = new UC3AgentActionMsg();
            this.target_action = new UC3AgentActionMsg();
        }

        public UC3EnvironmentStepRequest(BuiltinInterfaces.TimeMsg request_sent_timestamp, UC3AgentActionMsg action, UC3AgentActionMsg target_action)
        {
            this.request_sent_timestamp = request_sent_timestamp;
            this.action = action;
            this.target_action = target_action;
        }

        public static UC3EnvironmentStepRequest Deserialize(MessageDeserializer deserializer) => new UC3EnvironmentStepRequest(deserializer);

        private UC3EnvironmentStepRequest(MessageDeserializer deserializer)
        {
            this.request_sent_timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.action = UC3AgentActionMsg.Deserialize(deserializer);
            this.target_action = UC3AgentActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_sent_timestamp);
            serializer.Write(this.action);
            serializer.Write(this.target_action);
        }

        public override string ToString()
        {
            return "UC3EnvironmentStepRequest: " +
            "\nrequest_sent_timestamp: " + request_sent_timestamp.ToString() +
            "\naction: " + action.ToString() +
            "\ntarget_action: " + target_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
