//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class BotParamsMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/BotParams";
        public override string RosMessageName => k_RosMessageName;

        public bool reset;
        public float speed;
        public bool can_shoot;
        public bool follow_waypoints;
        public float range;
        public float fire_rate;
        public float turret_rotation_speed;
        public float angle_error;

        public BotParamsMsg()
        {
            this.reset = false;
            this.speed = 0.0f;
            this.can_shoot = false;
            this.follow_waypoints = false;
            this.range = 0.0f;
            this.fire_rate = 0.0f;
            this.turret_rotation_speed = 0.0f;
            this.angle_error = 0.0f;
        }

        public BotParamsMsg(bool reset, float speed, bool can_shoot, bool follow_waypoints, float range, float fire_rate, float turret_rotation_speed, float angle_error)
        {
            this.reset = reset;
            this.speed = speed;
            this.can_shoot = can_shoot;
            this.follow_waypoints = follow_waypoints;
            this.range = range;
            this.fire_rate = fire_rate;
            this.turret_rotation_speed = turret_rotation_speed;
            this.angle_error = angle_error;
        }

        public static BotParamsMsg Deserialize(MessageDeserializer deserializer) => new BotParamsMsg(deserializer);

        private BotParamsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.reset);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.can_shoot);
            deserializer.Read(out this.follow_waypoints);
            deserializer.Read(out this.range);
            deserializer.Read(out this.fire_rate);
            deserializer.Read(out this.turret_rotation_speed);
            deserializer.Read(out this.angle_error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.reset);
            serializer.Write(this.speed);
            serializer.Write(this.can_shoot);
            serializer.Write(this.follow_waypoints);
            serializer.Write(this.range);
            serializer.Write(this.fire_rate);
            serializer.Write(this.turret_rotation_speed);
            serializer.Write(this.angle_error);
        }

        public override string ToString()
        {
            return "BotParamsMsg: " +
            "\nreset: " + reset.ToString() +
            "\nspeed: " + speed.ToString() +
            "\ncan_shoot: " + can_shoot.ToString() +
            "\nfollow_waypoints: " + follow_waypoints.ToString() +
            "\nrange: " + range.ToString() +
            "\nfire_rate: " + fire_rate.ToString() +
            "\nturret_rotation_speed: " + turret_rotation_speed.ToString() +
            "\nangle_error: " + angle_error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
