//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class TargetTankStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/TargetTankState";
        public override string RosMessageName => k_RosMessageName;

        public Pose2DMsg pose;
        public Twist2DMsg twist;
        public HealthInfoMsg health_info;

        public TargetTankStateMsg()
        {
            this.pose = new Pose2DMsg();
            this.twist = new Twist2DMsg();
            this.health_info = new HealthInfoMsg();
        }

        public TargetTankStateMsg(Pose2DMsg pose, Twist2DMsg twist, HealthInfoMsg health_info)
        {
            this.pose = pose;
            this.twist = twist;
            this.health_info = health_info;
        }

        public static TargetTankStateMsg Deserialize(MessageDeserializer deserializer) => new TargetTankStateMsg(deserializer);

        private TargetTankStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Pose2DMsg.Deserialize(deserializer);
            this.twist = Twist2DMsg.Deserialize(deserializer);
            this.health_info = HealthInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.twist);
            serializer.Write(this.health_info);
        }

        public override string ToString()
        {
            return "TargetTankStateMsg: " +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString() +
            "\nhealth_info: " + health_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
