//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC2AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC2AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank;
        public EnemyTankStateMsg enemy_tank;

        public UC2AgentStateMsg()
        {
            this.tank = new TankStateMsg();
            this.enemy_tank = new EnemyTankStateMsg();
        }

        public UC2AgentStateMsg(TankStateMsg tank, EnemyTankStateMsg enemy_tank)
        {
            this.tank = tank;
            this.enemy_tank = enemy_tank;
        }

        public static UC2AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC2AgentStateMsg(deserializer);

        private UC2AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank = TankStateMsg.Deserialize(deserializer);
            this.enemy_tank = EnemyTankStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank);
            serializer.Write(this.enemy_tank);
        }

        public override string ToString()
        {
            return "UC2AgentStateMsg: " +
            "\ntank: " + tank.ToString() +
            "\nenemy_tank: " + enemy_tank.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
