//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterfacesPkg
{
    [Serializable]
    public class UC3AgentStateMsg : Message
    {
        public const string k_RosMessageName = "interfaces_pkg/UC3AgentState";
        public override string RosMessageName => k_RosMessageName;

        public TankStateMsg tank;
        public TargetTankStateMsg target_tank;

        public UC3AgentStateMsg()
        {
            this.tank = new TankStateMsg();
            this.target_tank = new TargetTankStateMsg();
        }

        public UC3AgentStateMsg(TankStateMsg tank, TargetTankStateMsg target_tank)
        {
            this.tank = tank;
            this.target_tank = target_tank;
        }

        public static UC3AgentStateMsg Deserialize(MessageDeserializer deserializer) => new UC3AgentStateMsg(deserializer);

        private UC3AgentStateMsg(MessageDeserializer deserializer)
        {
            this.tank = TankStateMsg.Deserialize(deserializer);
            this.target_tank = TargetTankStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tank);
            serializer.Write(this.target_tank);
        }

        public override string ToString()
        {
            return "UC3AgentStateMsg: " +
            "\ntank: " + tank.ToString() +
            "\ntarget_tank: " + target_tank.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
